module Icons exposing (icons)

import FontAwesome.Icon
import FontAwesome.Solid


icons : List FontAwesome.Icon.Icon
icons =
    [ FontAwesome.Solid.ad
    , FontAwesome.Solid.addressBook
    , FontAwesome.Solid.addressCard
    , FontAwesome.Solid.adjust
    , FontAwesome.Solid.airFreshener
    , FontAwesome.Solid.alignCenter
    , FontAwesome.Solid.alignJustify
    , FontAwesome.Solid.alignLeft
    , FontAwesome.Solid.alignRight
    , FontAwesome.Solid.allergies
    , FontAwesome.Solid.ambulance
    , FontAwesome.Solid.americanSignLanguageInterpreting
    , FontAwesome.Solid.anchor
    , FontAwesome.Solid.angleDoubleDown
    , FontAwesome.Solid.angleDoubleLeft
    , FontAwesome.Solid.angleDoubleRight
    , FontAwesome.Solid.angleDoubleUp
    , FontAwesome.Solid.angleDown
    , FontAwesome.Solid.angleLeft
    , FontAwesome.Solid.angleRight
    , FontAwesome.Solid.angleUp
    , FontAwesome.Solid.angry
    , FontAwesome.Solid.ankh
    , FontAwesome.Solid.appleAlt
    , FontAwesome.Solid.archive
    , FontAwesome.Solid.archway
    , FontAwesome.Solid.arrowAltCircleDown
    , FontAwesome.Solid.arrowAltCircleLeft
    , FontAwesome.Solid.arrowAltCircleRight
    , FontAwesome.Solid.arrowAltCircleUp
    , FontAwesome.Solid.arrowCircleDown
    , FontAwesome.Solid.arrowCircleLeft
    , FontAwesome.Solid.arrowCircleRight
    , FontAwesome.Solid.arrowCircleUp
    , FontAwesome.Solid.arrowDown
    , FontAwesome.Solid.arrowLeft
    , FontAwesome.Solid.arrowRight
    , FontAwesome.Solid.arrowUp
    , FontAwesome.Solid.arrowsAlt
    , FontAwesome.Solid.arrowsAltH
    , FontAwesome.Solid.arrowsAltV
    , FontAwesome.Solid.assistiveListeningSystems
    , FontAwesome.Solid.asterisk
    , FontAwesome.Solid.at
    , FontAwesome.Solid.atlas
    , FontAwesome.Solid.atom
    , FontAwesome.Solid.audioDescription
    , FontAwesome.Solid.award
    , FontAwesome.Solid.baby
    , FontAwesome.Solid.babyCarriage
    , FontAwesome.Solid.backspace
    , FontAwesome.Solid.backward
    , FontAwesome.Solid.bacon
    , FontAwesome.Solid.bacteria
    , FontAwesome.Solid.bacterium
    , FontAwesome.Solid.bahai
    , FontAwesome.Solid.balanceScale
    , FontAwesome.Solid.balanceScaleLeft
    , FontAwesome.Solid.balanceScaleRight
    , FontAwesome.Solid.ban
    , FontAwesome.Solid.bandAid
    , FontAwesome.Solid.barcode
    , FontAwesome.Solid.bars
    , FontAwesome.Solid.baseballBall
    , FontAwesome.Solid.basketballBall
    , FontAwesome.Solid.bath
    , FontAwesome.Solid.batteryEmpty
    , FontAwesome.Solid.batteryFull
    , FontAwesome.Solid.batteryHalf
    , FontAwesome.Solid.batteryQuarter
    , FontAwesome.Solid.batteryThreeQuarters
    , FontAwesome.Solid.bed
    , FontAwesome.Solid.beer
    , FontAwesome.Solid.bell
    , FontAwesome.Solid.bellSlash
    , FontAwesome.Solid.bezierCurve
    , FontAwesome.Solid.bible
    , FontAwesome.Solid.bicycle
    , FontAwesome.Solid.biking
    , FontAwesome.Solid.binoculars
    , FontAwesome.Solid.biohazard
    , FontAwesome.Solid.birthdayCake
    , FontAwesome.Solid.blender
    , FontAwesome.Solid.blenderPhone
    , FontAwesome.Solid.blind
    , FontAwesome.Solid.blog
    , FontAwesome.Solid.bold
    , FontAwesome.Solid.bolt
    , FontAwesome.Solid.bomb
    , FontAwesome.Solid.bone
    , FontAwesome.Solid.bong
    , FontAwesome.Solid.book
    , FontAwesome.Solid.bookDead
    , FontAwesome.Solid.bookMedical
    , FontAwesome.Solid.bookOpen
    , FontAwesome.Solid.bookReader
    , FontAwesome.Solid.bookmark
    , FontAwesome.Solid.borderAll
    , FontAwesome.Solid.borderNone
    , FontAwesome.Solid.borderStyle
    , FontAwesome.Solid.bowlingBall
    , FontAwesome.Solid.box
    , FontAwesome.Solid.boxOpen
    , FontAwesome.Solid.boxTissue
    , FontAwesome.Solid.boxes
    , FontAwesome.Solid.braille
    , FontAwesome.Solid.brain
    , FontAwesome.Solid.breadSlice
    , FontAwesome.Solid.briefcase
    , FontAwesome.Solid.briefcaseMedical
    , FontAwesome.Solid.broadcastTower
    , FontAwesome.Solid.broom
    , FontAwesome.Solid.brush
    , FontAwesome.Solid.bug
    , FontAwesome.Solid.building
    , FontAwesome.Solid.bullhorn
    , FontAwesome.Solid.bullseye
    , FontAwesome.Solid.burn
    , FontAwesome.Solid.bus
    , FontAwesome.Solid.busAlt
    , FontAwesome.Solid.businessTime
    , FontAwesome.Solid.calculator
    , FontAwesome.Solid.calendar
    , FontAwesome.Solid.calendarAlt
    , FontAwesome.Solid.calendarCheck
    , FontAwesome.Solid.calendarDay
    , FontAwesome.Solid.calendarMinus
    , FontAwesome.Solid.calendarPlus
    , FontAwesome.Solid.calendarTimes
    , FontAwesome.Solid.calendarWeek
    , FontAwesome.Solid.camera
    , FontAwesome.Solid.cameraRetro
    , FontAwesome.Solid.campground
    , FontAwesome.Solid.candyCane
    , FontAwesome.Solid.cannabis
    , FontAwesome.Solid.capsules
    , FontAwesome.Solid.car
    , FontAwesome.Solid.carAlt
    , FontAwesome.Solid.carBattery
    , FontAwesome.Solid.carCrash
    , FontAwesome.Solid.carSide
    , FontAwesome.Solid.caravan
    , FontAwesome.Solid.caretDown
    , FontAwesome.Solid.caretLeft
    , FontAwesome.Solid.caretRight
    , FontAwesome.Solid.caretSquareDown
    , FontAwesome.Solid.caretSquareLeft
    , FontAwesome.Solid.caretSquareRight
    , FontAwesome.Solid.caretSquareUp
    , FontAwesome.Solid.caretUp
    , FontAwesome.Solid.carrot
    , FontAwesome.Solid.cartArrowDown
    , FontAwesome.Solid.cartPlus
    , FontAwesome.Solid.cashRegister
    , FontAwesome.Solid.cat
    , FontAwesome.Solid.certificate
    , FontAwesome.Solid.chair
    , FontAwesome.Solid.chalkboard
    , FontAwesome.Solid.chalkboardTeacher
    , FontAwesome.Solid.chargingStation
    , FontAwesome.Solid.chartArea
    , FontAwesome.Solid.chartBar
    , FontAwesome.Solid.chartLine
    , FontAwesome.Solid.chartPie
    , FontAwesome.Solid.check
    , FontAwesome.Solid.checkCircle
    , FontAwesome.Solid.checkDouble
    , FontAwesome.Solid.checkSquare
    , FontAwesome.Solid.cheese
    , FontAwesome.Solid.chess
    , FontAwesome.Solid.chessBishop
    , FontAwesome.Solid.chessBoard
    , FontAwesome.Solid.chessKing
    , FontAwesome.Solid.chessKnight
    , FontAwesome.Solid.chessPawn
    , FontAwesome.Solid.chessQueen
    , FontAwesome.Solid.chessRook
    , FontAwesome.Solid.chevronCircleDown
    , FontAwesome.Solid.chevronCircleLeft
    , FontAwesome.Solid.chevronCircleRight
    , FontAwesome.Solid.chevronCircleUp
    , FontAwesome.Solid.chevronDown
    , FontAwesome.Solid.chevronLeft
    , FontAwesome.Solid.chevronRight
    , FontAwesome.Solid.chevronUp
    , FontAwesome.Solid.child
    , FontAwesome.Solid.church
    , FontAwesome.Solid.circle
    , FontAwesome.Solid.circleNotch
    , FontAwesome.Solid.city
    , FontAwesome.Solid.clinicMedical
    , FontAwesome.Solid.clipboard
    , FontAwesome.Solid.clipboardCheck
    , FontAwesome.Solid.clipboardList
    , FontAwesome.Solid.clock
    , FontAwesome.Solid.clone
    , FontAwesome.Solid.closedCaptioning
    , FontAwesome.Solid.cloud
    , FontAwesome.Solid.cloudDownloadAlt
    , FontAwesome.Solid.cloudMeatball
    , FontAwesome.Solid.cloudMoon
    , FontAwesome.Solid.cloudMoonRain
    , FontAwesome.Solid.cloudRain
    , FontAwesome.Solid.cloudShowersHeavy
    , FontAwesome.Solid.cloudSun
    , FontAwesome.Solid.cloudSunRain
    , FontAwesome.Solid.cloudUploadAlt
    , FontAwesome.Solid.cocktail
    , FontAwesome.Solid.code
    , FontAwesome.Solid.codeBranch
    , FontAwesome.Solid.coffee
    , FontAwesome.Solid.cog
    , FontAwesome.Solid.cogs
    , FontAwesome.Solid.coins
    , FontAwesome.Solid.columns
    , FontAwesome.Solid.comment
    , FontAwesome.Solid.commentAlt
    , FontAwesome.Solid.commentDollar
    , FontAwesome.Solid.commentDots
    , FontAwesome.Solid.commentMedical
    , FontAwesome.Solid.commentSlash
    , FontAwesome.Solid.comments
    , FontAwesome.Solid.commentsDollar
    , FontAwesome.Solid.compactDisc
    , FontAwesome.Solid.compass
    , FontAwesome.Solid.compress
    , FontAwesome.Solid.compressAlt
    , FontAwesome.Solid.compressArrowsAlt
    , FontAwesome.Solid.conciergeBell
    , FontAwesome.Solid.cookie
    , FontAwesome.Solid.cookieBite
    , FontAwesome.Solid.copy
    , FontAwesome.Solid.copyright
    , FontAwesome.Solid.couch
    , FontAwesome.Solid.creditCard
    , FontAwesome.Solid.crop
    , FontAwesome.Solid.cropAlt
    , FontAwesome.Solid.cross
    , FontAwesome.Solid.crosshairs
    , FontAwesome.Solid.crow
    , FontAwesome.Solid.crown
    , FontAwesome.Solid.crutch
    , FontAwesome.Solid.cube
    , FontAwesome.Solid.cubes
    , FontAwesome.Solid.cut
    , FontAwesome.Solid.database
    , FontAwesome.Solid.deaf
    , FontAwesome.Solid.democrat
    , FontAwesome.Solid.desktop
    , FontAwesome.Solid.dharmachakra
    , FontAwesome.Solid.diagnoses
    , FontAwesome.Solid.dice
    , FontAwesome.Solid.diceD20
    , FontAwesome.Solid.diceD6
    , FontAwesome.Solid.diceFive
    , FontAwesome.Solid.diceFour
    , FontAwesome.Solid.diceOne
    , FontAwesome.Solid.diceSix
    , FontAwesome.Solid.diceThree
    , FontAwesome.Solid.diceTwo
    , FontAwesome.Solid.digitalTachograph
    , FontAwesome.Solid.directions
    , FontAwesome.Solid.disease
    , FontAwesome.Solid.divide
    , FontAwesome.Solid.dizzy
    , FontAwesome.Solid.dna
    , FontAwesome.Solid.dog
    , FontAwesome.Solid.dollarSign
    , FontAwesome.Solid.dolly
    , FontAwesome.Solid.dollyFlatbed
    , FontAwesome.Solid.donate
    , FontAwesome.Solid.doorClosed
    , FontAwesome.Solid.doorOpen
    , FontAwesome.Solid.dotCircle
    , FontAwesome.Solid.dove
    , FontAwesome.Solid.download
    , FontAwesome.Solid.draftingCompass
    , FontAwesome.Solid.dragon
    , FontAwesome.Solid.drawPolygon
    , FontAwesome.Solid.drum
    , FontAwesome.Solid.drumSteelpan
    , FontAwesome.Solid.drumstickBite
    , FontAwesome.Solid.dumbbell
    , FontAwesome.Solid.dumpster
    , FontAwesome.Solid.dumpsterFire
    , FontAwesome.Solid.dungeon
    , FontAwesome.Solid.edit
    , FontAwesome.Solid.egg
    , FontAwesome.Solid.eject
    , FontAwesome.Solid.ellipsisH
    , FontAwesome.Solid.ellipsisV
    , FontAwesome.Solid.envelope
    , FontAwesome.Solid.envelopeOpen
    , FontAwesome.Solid.envelopeOpenText
    , FontAwesome.Solid.envelopeSquare
    , FontAwesome.Solid.equals
    , FontAwesome.Solid.eraser
    , FontAwesome.Solid.ethernet
    , FontAwesome.Solid.euroSign
    , FontAwesome.Solid.exchangeAlt
    , FontAwesome.Solid.exclamation
    , FontAwesome.Solid.exclamationCircle
    , FontAwesome.Solid.exclamationTriangle
    , FontAwesome.Solid.expand
    , FontAwesome.Solid.expandAlt
    , FontAwesome.Solid.expandArrowsAlt
    , FontAwesome.Solid.externalLinkAlt
    , FontAwesome.Solid.externalLinkSquareAlt
    , FontAwesome.Solid.eye
    , FontAwesome.Solid.eyeDropper
    , FontAwesome.Solid.eyeSlash
    , FontAwesome.Solid.fan
    , FontAwesome.Solid.fastBackward
    , FontAwesome.Solid.fastForward
    , FontAwesome.Solid.faucet
    , FontAwesome.Solid.fax
    , FontAwesome.Solid.feather
    , FontAwesome.Solid.featherAlt
    , FontAwesome.Solid.female
    , FontAwesome.Solid.fighterJet
    , FontAwesome.Solid.file
    , FontAwesome.Solid.fileAlt
    , FontAwesome.Solid.fileArchive
    , FontAwesome.Solid.fileAudio
    , FontAwesome.Solid.fileCode
    , FontAwesome.Solid.fileContract
    , FontAwesome.Solid.fileCsv
    , FontAwesome.Solid.fileDownload
    , FontAwesome.Solid.fileExcel
    , FontAwesome.Solid.fileExport
    , FontAwesome.Solid.fileImage
    , FontAwesome.Solid.fileImport
    , FontAwesome.Solid.fileInvoice
    , FontAwesome.Solid.fileInvoiceDollar
    , FontAwesome.Solid.fileMedical
    , FontAwesome.Solid.fileMedicalAlt
    , FontAwesome.Solid.filePdf
    , FontAwesome.Solid.filePowerpoint
    , FontAwesome.Solid.filePrescription
    , FontAwesome.Solid.fileSignature
    , FontAwesome.Solid.fileUpload
    , FontAwesome.Solid.fileVideo
    , FontAwesome.Solid.fileWord
    , FontAwesome.Solid.fill
    , FontAwesome.Solid.fillDrip
    , FontAwesome.Solid.film
    , FontAwesome.Solid.filter
    , FontAwesome.Solid.fingerprint
    , FontAwesome.Solid.fire
    , FontAwesome.Solid.fireAlt
    , FontAwesome.Solid.fireExtinguisher
    , FontAwesome.Solid.firstAid
    , FontAwesome.Solid.fish
    , FontAwesome.Solid.fistRaised
    , FontAwesome.Solid.flag
    , FontAwesome.Solid.flagCheckered
    , FontAwesome.Solid.flagUsa
    , FontAwesome.Solid.flask
    , FontAwesome.Solid.flushed
    , FontAwesome.Solid.folder
    , FontAwesome.Solid.folderMinus
    , FontAwesome.Solid.folderOpen
    , FontAwesome.Solid.folderPlus
    , FontAwesome.Solid.font
    , FontAwesome.Solid.fontAwesomeLogoFull
    , FontAwesome.Solid.footballBall
    , FontAwesome.Solid.forward
    , FontAwesome.Solid.frog
    , FontAwesome.Solid.frown
    , FontAwesome.Solid.frownOpen
    , FontAwesome.Solid.funnelDollar
    , FontAwesome.Solid.futbol
    , FontAwesome.Solid.gamepad
    , FontAwesome.Solid.gasPump
    , FontAwesome.Solid.gavel
    , FontAwesome.Solid.gem
    , FontAwesome.Solid.genderless
    , FontAwesome.Solid.ghost
    , FontAwesome.Solid.gift
    , FontAwesome.Solid.gifts
    , FontAwesome.Solid.glassCheers
    , FontAwesome.Solid.glassMartini
    , FontAwesome.Solid.glassMartiniAlt
    , FontAwesome.Solid.glassWhiskey
    , FontAwesome.Solid.glasses
    , FontAwesome.Solid.globe
    , FontAwesome.Solid.globeAfrica
    , FontAwesome.Solid.globeAmericas
    , FontAwesome.Solid.globeAsia
    , FontAwesome.Solid.globeEurope
    , FontAwesome.Solid.golfBall
    , FontAwesome.Solid.gopuram
    , FontAwesome.Solid.graduationCap
    , FontAwesome.Solid.greaterThan
    , FontAwesome.Solid.greaterThanEqual
    , FontAwesome.Solid.grimace
    , FontAwesome.Solid.grin
    , FontAwesome.Solid.grinAlt
    , FontAwesome.Solid.grinBeam
    , FontAwesome.Solid.grinBeamSweat
    , FontAwesome.Solid.grinHearts
    , FontAwesome.Solid.grinSquint
    , FontAwesome.Solid.grinSquintTears
    , FontAwesome.Solid.grinStars
    , FontAwesome.Solid.grinTears
    , FontAwesome.Solid.grinTongue
    , FontAwesome.Solid.grinTongueSquint
    , FontAwesome.Solid.grinTongueWink
    , FontAwesome.Solid.grinWink
    , FontAwesome.Solid.gripHorizontal
    , FontAwesome.Solid.gripLines
    , FontAwesome.Solid.gripLinesVertical
    , FontAwesome.Solid.gripVertical
    , FontAwesome.Solid.guitar
    , FontAwesome.Solid.hSquare
    , FontAwesome.Solid.hamburger
    , FontAwesome.Solid.hammer
    , FontAwesome.Solid.hamsa
    , FontAwesome.Solid.handHolding
    , FontAwesome.Solid.handHoldingHeart
    , FontAwesome.Solid.handHoldingMedical
    , FontAwesome.Solid.handHoldingUsd
    , FontAwesome.Solid.handHoldingWater
    , FontAwesome.Solid.handLizard
    , FontAwesome.Solid.handMiddleFinger
    , FontAwesome.Solid.handPaper
    , FontAwesome.Solid.handPeace
    , FontAwesome.Solid.handPointDown
    , FontAwesome.Solid.handPointLeft
    , FontAwesome.Solid.handPointRight
    , FontAwesome.Solid.handPointUp
    , FontAwesome.Solid.handPointer
    , FontAwesome.Solid.handRock
    , FontAwesome.Solid.handScissors
    , FontAwesome.Solid.handSparkles
    , FontAwesome.Solid.handSpock
    , FontAwesome.Solid.hands
    , FontAwesome.Solid.handsHelping
    , FontAwesome.Solid.handsWash
    , FontAwesome.Solid.handshake
    , FontAwesome.Solid.handshakeAltSlash
    , FontAwesome.Solid.handshakeSlash
    , FontAwesome.Solid.hanukiah
    , FontAwesome.Solid.hardHat
    , FontAwesome.Solid.hashtag
    , FontAwesome.Solid.hatCowboy
    , FontAwesome.Solid.hatCowboySide
    , FontAwesome.Solid.hatWizard
    , FontAwesome.Solid.hdd
    , FontAwesome.Solid.headSideCough
    , FontAwesome.Solid.headSideCoughSlash
    , FontAwesome.Solid.headSideMask
    , FontAwesome.Solid.headSideVirus
    , FontAwesome.Solid.heading
    , FontAwesome.Solid.headphones
    , FontAwesome.Solid.headphonesAlt
    , FontAwesome.Solid.headset
    , FontAwesome.Solid.heart
    , FontAwesome.Solid.heartBroken
    , FontAwesome.Solid.heartbeat
    , FontAwesome.Solid.helicopter
    , FontAwesome.Solid.highlighter
    , FontAwesome.Solid.hiking
    , FontAwesome.Solid.hippo
    , FontAwesome.Solid.history
    , FontAwesome.Solid.hockeyPuck
    , FontAwesome.Solid.hollyBerry
    , FontAwesome.Solid.home
    , FontAwesome.Solid.horse
    , FontAwesome.Solid.horseHead
    , FontAwesome.Solid.hospital
    , FontAwesome.Solid.hospitalAlt
    , FontAwesome.Solid.hospitalSymbol
    , FontAwesome.Solid.hospitalUser
    , FontAwesome.Solid.hotTub
    , FontAwesome.Solid.hotdog
    , FontAwesome.Solid.hotel
    , FontAwesome.Solid.hourglass
    , FontAwesome.Solid.hourglassEnd
    , FontAwesome.Solid.hourglassHalf
    , FontAwesome.Solid.hourglassStart
    , FontAwesome.Solid.houseDamage
    , FontAwesome.Solid.houseUser
    , FontAwesome.Solid.hryvnia
    , FontAwesome.Solid.iCursor
    , FontAwesome.Solid.iceCream
    , FontAwesome.Solid.icicles
    , FontAwesome.Solid.icons
    , FontAwesome.Solid.idBadge
    , FontAwesome.Solid.idCard
    , FontAwesome.Solid.idCardAlt
    , FontAwesome.Solid.igloo
    , FontAwesome.Solid.image
    , FontAwesome.Solid.images
    , FontAwesome.Solid.inbox
    , FontAwesome.Solid.indent
    , FontAwesome.Solid.industry
    , FontAwesome.Solid.infinity
    , FontAwesome.Solid.info
    , FontAwesome.Solid.infoCircle
    , FontAwesome.Solid.italic
    , FontAwesome.Solid.jedi
    , FontAwesome.Solid.joint
    , FontAwesome.Solid.journalWhills
    , FontAwesome.Solid.kaaba
    , FontAwesome.Solid.key
    , FontAwesome.Solid.keyboard
    , FontAwesome.Solid.khanda
    , FontAwesome.Solid.kiss
    , FontAwesome.Solid.kissBeam
    , FontAwesome.Solid.kissWinkHeart
    , FontAwesome.Solid.kiwiBird
    , FontAwesome.Solid.landmark
    , FontAwesome.Solid.language
    , FontAwesome.Solid.laptop
    , FontAwesome.Solid.laptopCode
    , FontAwesome.Solid.laptopHouse
    , FontAwesome.Solid.laptopMedical
    , FontAwesome.Solid.laugh
    , FontAwesome.Solid.laughBeam
    , FontAwesome.Solid.laughSquint
    , FontAwesome.Solid.laughWink
    , FontAwesome.Solid.layerGroup
    , FontAwesome.Solid.leaf
    , FontAwesome.Solid.lemon
    , FontAwesome.Solid.lessThan
    , FontAwesome.Solid.lessThanEqual
    , FontAwesome.Solid.levelDownAlt
    , FontAwesome.Solid.levelUpAlt
    , FontAwesome.Solid.lifeRing
    , FontAwesome.Solid.lightbulb
    , FontAwesome.Solid.link
    , FontAwesome.Solid.liraSign
    , FontAwesome.Solid.list
    , FontAwesome.Solid.listAlt
    , FontAwesome.Solid.listOl
    , FontAwesome.Solid.listUl
    , FontAwesome.Solid.locationArrow
    , FontAwesome.Solid.lock
    , FontAwesome.Solid.lockOpen
    , FontAwesome.Solid.longArrowAltDown
    , FontAwesome.Solid.longArrowAltLeft
    , FontAwesome.Solid.longArrowAltRight
    , FontAwesome.Solid.longArrowAltUp
    , FontAwesome.Solid.lowVision
    , FontAwesome.Solid.luggageCart
    , FontAwesome.Solid.lungs
    , FontAwesome.Solid.lungsVirus
    , FontAwesome.Solid.magic
    , FontAwesome.Solid.magnet
    , FontAwesome.Solid.mailBulk
    , FontAwesome.Solid.male
    , FontAwesome.Solid.map
    , FontAwesome.Solid.mapMarked
    , FontAwesome.Solid.mapMarkedAlt
    , FontAwesome.Solid.mapMarker
    , FontAwesome.Solid.mapMarkerAlt
    , FontAwesome.Solid.mapPin
    , FontAwesome.Solid.mapSigns
    , FontAwesome.Solid.marker
    , FontAwesome.Solid.mars
    , FontAwesome.Solid.marsDouble
    , FontAwesome.Solid.marsStroke
    , FontAwesome.Solid.marsStrokeH
    , FontAwesome.Solid.marsStrokeV
    , FontAwesome.Solid.mask
    , FontAwesome.Solid.medal
    , FontAwesome.Solid.medkit
    , FontAwesome.Solid.meh
    , FontAwesome.Solid.mehBlank
    , FontAwesome.Solid.mehRollingEyes
    , FontAwesome.Solid.memory
    , FontAwesome.Solid.menorah
    , FontAwesome.Solid.mercury
    , FontAwesome.Solid.meteor
    , FontAwesome.Solid.microchip
    , FontAwesome.Solid.microphone
    , FontAwesome.Solid.microphoneAlt
    , FontAwesome.Solid.microphoneAltSlash
    , FontAwesome.Solid.microphoneSlash
    , FontAwesome.Solid.microscope
    , FontAwesome.Solid.minus
    , FontAwesome.Solid.minusCircle
    , FontAwesome.Solid.minusSquare
    , FontAwesome.Solid.mitten
    , FontAwesome.Solid.mobile
    , FontAwesome.Solid.mobileAlt
    , FontAwesome.Solid.moneyBill
    , FontAwesome.Solid.moneyBillAlt
    , FontAwesome.Solid.moneyBillWave
    , FontAwesome.Solid.moneyBillWaveAlt
    , FontAwesome.Solid.moneyCheck
    , FontAwesome.Solid.moneyCheckAlt
    , FontAwesome.Solid.monument
    , FontAwesome.Solid.moon
    , FontAwesome.Solid.mortarPestle
    , FontAwesome.Solid.mosque
    , FontAwesome.Solid.motorcycle
    , FontAwesome.Solid.mountain
    , FontAwesome.Solid.mouse
    , FontAwesome.Solid.mousePointer
    , FontAwesome.Solid.mugHot
    , FontAwesome.Solid.music
    , FontAwesome.Solid.networkWired
    , FontAwesome.Solid.neuter
    , FontAwesome.Solid.newspaper
    , FontAwesome.Solid.notEqual
    , FontAwesome.Solid.notesMedical
    , FontAwesome.Solid.objectGroup
    , FontAwesome.Solid.objectUngroup
    , FontAwesome.Solid.oilCan
    , FontAwesome.Solid.om
    , FontAwesome.Solid.otter
    , FontAwesome.Solid.outdent
    , FontAwesome.Solid.pager
    , FontAwesome.Solid.paintBrush
    , FontAwesome.Solid.paintRoller
    , FontAwesome.Solid.palette
    , FontAwesome.Solid.pallet
    , FontAwesome.Solid.paperPlane
    , FontAwesome.Solid.paperclip
    , FontAwesome.Solid.parachuteBox
    , FontAwesome.Solid.paragraph
    , FontAwesome.Solid.parking
    , FontAwesome.Solid.passport
    , FontAwesome.Solid.pastafarianism
    , FontAwesome.Solid.paste
    , FontAwesome.Solid.pause
    , FontAwesome.Solid.pauseCircle
    , FontAwesome.Solid.paw
    , FontAwesome.Solid.peace
    , FontAwesome.Solid.pen
    , FontAwesome.Solid.penAlt
    , FontAwesome.Solid.penFancy
    , FontAwesome.Solid.penNib
    , FontAwesome.Solid.penSquare
    , FontAwesome.Solid.pencilAlt
    , FontAwesome.Solid.pencilRuler
    , FontAwesome.Solid.peopleArrows
    , FontAwesome.Solid.peopleCarry
    , FontAwesome.Solid.pepperHot
    , FontAwesome.Solid.percent
    , FontAwesome.Solid.percentage
    , FontAwesome.Solid.personBooth
    , FontAwesome.Solid.phone
    , FontAwesome.Solid.phoneAlt
    , FontAwesome.Solid.phoneSlash
    , FontAwesome.Solid.phoneSquare
    , FontAwesome.Solid.phoneSquareAlt
    , FontAwesome.Solid.phoneVolume
    , FontAwesome.Solid.photoVideo
    , FontAwesome.Solid.piggyBank
    , FontAwesome.Solid.pills
    , FontAwesome.Solid.pizzaSlice
    , FontAwesome.Solid.placeOfWorship
    , FontAwesome.Solid.plane
    , FontAwesome.Solid.planeArrival
    , FontAwesome.Solid.planeDeparture
    , FontAwesome.Solid.planeSlash
    , FontAwesome.Solid.play
    , FontAwesome.Solid.playCircle
    , FontAwesome.Solid.plug
    , FontAwesome.Solid.plus
    , FontAwesome.Solid.plusCircle
    , FontAwesome.Solid.plusSquare
    , FontAwesome.Solid.podcast
    , FontAwesome.Solid.poll
    , FontAwesome.Solid.pollH
    , FontAwesome.Solid.poo
    , FontAwesome.Solid.pooStorm
    , FontAwesome.Solid.poop
    , FontAwesome.Solid.portrait
    , FontAwesome.Solid.poundSign
    , FontAwesome.Solid.powerOff
    , FontAwesome.Solid.pray
    , FontAwesome.Solid.prayingHands
    , FontAwesome.Solid.prescription
    , FontAwesome.Solid.prescriptionBottle
    , FontAwesome.Solid.prescriptionBottleAlt
    , FontAwesome.Solid.print
    , FontAwesome.Solid.procedures
    , FontAwesome.Solid.projectDiagram
    , FontAwesome.Solid.pumpMedical
    , FontAwesome.Solid.pumpSoap
    , FontAwesome.Solid.puzzlePiece
    , FontAwesome.Solid.qrcode
    , FontAwesome.Solid.question
    , FontAwesome.Solid.questionCircle
    , FontAwesome.Solid.quidditch
    , FontAwesome.Solid.quoteLeft
    , FontAwesome.Solid.quoteRight
    , FontAwesome.Solid.quran
    , FontAwesome.Solid.radiation
    , FontAwesome.Solid.radiationAlt
    , FontAwesome.Solid.rainbow
    , FontAwesome.Solid.random
    , FontAwesome.Solid.receipt
    , FontAwesome.Solid.recordVinyl
    , FontAwesome.Solid.recycle
    , FontAwesome.Solid.redo
    , FontAwesome.Solid.redoAlt
    , FontAwesome.Solid.registered
    , FontAwesome.Solid.removeFormat
    , FontAwesome.Solid.reply
    , FontAwesome.Solid.replyAll
    , FontAwesome.Solid.republican
    , FontAwesome.Solid.restroom
    , FontAwesome.Solid.retweet
    , FontAwesome.Solid.ribbon
    , FontAwesome.Solid.ring
    , FontAwesome.Solid.road
    , FontAwesome.Solid.robot
    , FontAwesome.Solid.rocket
    , FontAwesome.Solid.route
    , FontAwesome.Solid.rss
    , FontAwesome.Solid.rssSquare
    , FontAwesome.Solid.rubleSign
    , FontAwesome.Solid.ruler
    , FontAwesome.Solid.rulerCombined
    , FontAwesome.Solid.rulerHorizontal
    , FontAwesome.Solid.rulerVertical
    , FontAwesome.Solid.running
    , FontAwesome.Solid.rupeeSign
    , FontAwesome.Solid.sadCry
    , FontAwesome.Solid.sadTear
    , FontAwesome.Solid.satellite
    , FontAwesome.Solid.satelliteDish
    , FontAwesome.Solid.save
    , FontAwesome.Solid.school
    , FontAwesome.Solid.screwdriver
    , FontAwesome.Solid.scroll
    , FontAwesome.Solid.sdCard
    , FontAwesome.Solid.search
    , FontAwesome.Solid.searchDollar
    , FontAwesome.Solid.searchLocation
    , FontAwesome.Solid.searchMinus
    , FontAwesome.Solid.searchPlus
    , FontAwesome.Solid.seedling
    , FontAwesome.Solid.server
    , FontAwesome.Solid.shapes
    , FontAwesome.Solid.share
    , FontAwesome.Solid.shareAlt
    , FontAwesome.Solid.shareAltSquare
    , FontAwesome.Solid.shareSquare
    , FontAwesome.Solid.shekelSign
    , FontAwesome.Solid.shieldAlt
    , FontAwesome.Solid.shieldVirus
    , FontAwesome.Solid.ship
    , FontAwesome.Solid.shippingFast
    , FontAwesome.Solid.shoePrints
    , FontAwesome.Solid.shoppingBag
    , FontAwesome.Solid.shoppingBasket
    , FontAwesome.Solid.shoppingCart
    , FontAwesome.Solid.shower
    , FontAwesome.Solid.shuttleVan
    , FontAwesome.Solid.sign
    , FontAwesome.Solid.signInAlt
    , FontAwesome.Solid.signLanguage
    , FontAwesome.Solid.signOutAlt
    , FontAwesome.Solid.signal
    , FontAwesome.Solid.signature
    , FontAwesome.Solid.simCard
    , FontAwesome.Solid.sink
    , FontAwesome.Solid.sitemap
    , FontAwesome.Solid.skating
    , FontAwesome.Solid.skiing
    , FontAwesome.Solid.skiingNordic
    , FontAwesome.Solid.skull
    , FontAwesome.Solid.skullCrossbones
    , FontAwesome.Solid.slash
    , FontAwesome.Solid.sleigh
    , FontAwesome.Solid.slidersH
    , FontAwesome.Solid.smile
    , FontAwesome.Solid.smileBeam
    , FontAwesome.Solid.smileWink
    , FontAwesome.Solid.smog
    , FontAwesome.Solid.smoking
    , FontAwesome.Solid.smokingBan
    , FontAwesome.Solid.sms
    , FontAwesome.Solid.snowboarding
    , FontAwesome.Solid.snowflake
    , FontAwesome.Solid.snowman
    , FontAwesome.Solid.snowplow
    , FontAwesome.Solid.soap
    , FontAwesome.Solid.socks
    , FontAwesome.Solid.solarPanel
    , FontAwesome.Solid.sort
    , FontAwesome.Solid.sortAlphaDown
    , FontAwesome.Solid.sortAlphaDownAlt
    , FontAwesome.Solid.sortAlphaUp
    , FontAwesome.Solid.sortAlphaUpAlt
    , FontAwesome.Solid.sortAmountDown
    , FontAwesome.Solid.sortAmountDownAlt
    , FontAwesome.Solid.sortAmountUp
    , FontAwesome.Solid.sortAmountUpAlt
    , FontAwesome.Solid.sortDown
    , FontAwesome.Solid.sortNumericDown
    , FontAwesome.Solid.sortNumericDownAlt
    , FontAwesome.Solid.sortNumericUp
    , FontAwesome.Solid.sortNumericUpAlt
    , FontAwesome.Solid.sortUp
    , FontAwesome.Solid.spa
    , FontAwesome.Solid.spaceShuttle
    , FontAwesome.Solid.spellCheck
    , FontAwesome.Solid.spider
    , FontAwesome.Solid.spinner
    , FontAwesome.Solid.splotch
    , FontAwesome.Solid.sprayCan
    , FontAwesome.Solid.square
    , FontAwesome.Solid.squareFull
    , FontAwesome.Solid.squareRootAlt
    , FontAwesome.Solid.stamp
    , FontAwesome.Solid.star
    , FontAwesome.Solid.starAndCrescent
    , FontAwesome.Solid.starHalf
    , FontAwesome.Solid.starHalfAlt
    , FontAwesome.Solid.starOfDavid
    , FontAwesome.Solid.starOfLife
    , FontAwesome.Solid.stepBackward
    , FontAwesome.Solid.stepForward
    , FontAwesome.Solid.stethoscope
    , FontAwesome.Solid.stickyNote
    , FontAwesome.Solid.stop
    , FontAwesome.Solid.stopCircle
    , FontAwesome.Solid.stopwatch
    , FontAwesome.Solid.stopwatch20
    , FontAwesome.Solid.store
    , FontAwesome.Solid.storeAlt
    , FontAwesome.Solid.storeAltSlash
    , FontAwesome.Solid.storeSlash
    , FontAwesome.Solid.stream
    , FontAwesome.Solid.streetView
    , FontAwesome.Solid.strikethrough
    , FontAwesome.Solid.stroopwafel
    , FontAwesome.Solid.subscript
    , FontAwesome.Solid.subway
    , FontAwesome.Solid.suitcase
    , FontAwesome.Solid.suitcaseRolling
    , FontAwesome.Solid.sun
    , FontAwesome.Solid.superscript
    , FontAwesome.Solid.surprise
    , FontAwesome.Solid.swatchbook
    , FontAwesome.Solid.swimmer
    , FontAwesome.Solid.swimmingPool
    , FontAwesome.Solid.synagogue
    , FontAwesome.Solid.sync
    , FontAwesome.Solid.syncAlt
    , FontAwesome.Solid.syringe
    , FontAwesome.Solid.table
    , FontAwesome.Solid.tableTennis
    , FontAwesome.Solid.tablet
    , FontAwesome.Solid.tabletAlt
    , FontAwesome.Solid.tablets
    , FontAwesome.Solid.tachometerAlt
    , FontAwesome.Solid.tag
    , FontAwesome.Solid.tags
    , FontAwesome.Solid.tape
    , FontAwesome.Solid.tasks
    , FontAwesome.Solid.taxi
    , FontAwesome.Solid.teeth
    , FontAwesome.Solid.teethOpen
    , FontAwesome.Solid.temperatureHigh
    , FontAwesome.Solid.temperatureLow
    , FontAwesome.Solid.tenge
    , FontAwesome.Solid.terminal
    , FontAwesome.Solid.textHeight
    , FontAwesome.Solid.textWidth
    , FontAwesome.Solid.th
    , FontAwesome.Solid.thLarge
    , FontAwesome.Solid.thList
    , FontAwesome.Solid.theaterMasks
    , FontAwesome.Solid.thermometer
    , FontAwesome.Solid.thermometerEmpty
    , FontAwesome.Solid.thermometerFull
    , FontAwesome.Solid.thermometerHalf
    , FontAwesome.Solid.thermometerQuarter
    , FontAwesome.Solid.thermometerThreeQuarters
    , FontAwesome.Solid.thumbsDown
    , FontAwesome.Solid.thumbsUp
    , FontAwesome.Solid.thumbtack
    , FontAwesome.Solid.ticketAlt
    , FontAwesome.Solid.times
    , FontAwesome.Solid.timesCircle
    , FontAwesome.Solid.tint
    , FontAwesome.Solid.tintSlash
    , FontAwesome.Solid.tired
    , FontAwesome.Solid.toggleOff
    , FontAwesome.Solid.toggleOn
    , FontAwesome.Solid.toilet
    , FontAwesome.Solid.toiletPaper
    , FontAwesome.Solid.toiletPaperSlash
    , FontAwesome.Solid.toolbox
    , FontAwesome.Solid.tools
    , FontAwesome.Solid.tooth
    , FontAwesome.Solid.torah
    , FontAwesome.Solid.toriiGate
    , FontAwesome.Solid.tractor
    , FontAwesome.Solid.trademark
    , FontAwesome.Solid.trafficLight
    , FontAwesome.Solid.trailer
    , FontAwesome.Solid.train
    , FontAwesome.Solid.tram
    , FontAwesome.Solid.transgender
    , FontAwesome.Solid.transgenderAlt
    , FontAwesome.Solid.trash
    , FontAwesome.Solid.trashAlt
    , FontAwesome.Solid.trashRestore
    , FontAwesome.Solid.trashRestoreAlt
    , FontAwesome.Solid.tree
    , FontAwesome.Solid.trophy
    , FontAwesome.Solid.truck
    , FontAwesome.Solid.truckLoading
    , FontAwesome.Solid.truckMonster
    , FontAwesome.Solid.truckMoving
    , FontAwesome.Solid.truckPickup
    , FontAwesome.Solid.tshirt
    , FontAwesome.Solid.tty
    , FontAwesome.Solid.tv
    , FontAwesome.Solid.umbrella
    , FontAwesome.Solid.umbrellaBeach
    , FontAwesome.Solid.underline
    , FontAwesome.Solid.undo
    , FontAwesome.Solid.undoAlt
    , FontAwesome.Solid.universalAccess
    , FontAwesome.Solid.university
    , FontAwesome.Solid.unlink
    , FontAwesome.Solid.unlock
    , FontAwesome.Solid.unlockAlt
    , FontAwesome.Solid.upload
    , FontAwesome.Solid.user
    , FontAwesome.Solid.userAlt
    , FontAwesome.Solid.userAltSlash
    , FontAwesome.Solid.userAstronaut
    , FontAwesome.Solid.userCheck
    , FontAwesome.Solid.userCircle
    , FontAwesome.Solid.userClock
    , FontAwesome.Solid.userCog
    , FontAwesome.Solid.userEdit
    , FontAwesome.Solid.userFriends
    , FontAwesome.Solid.userGraduate
    , FontAwesome.Solid.userInjured
    , FontAwesome.Solid.userLock
    , FontAwesome.Solid.userMd
    , FontAwesome.Solid.userMinus
    , FontAwesome.Solid.userNinja
    , FontAwesome.Solid.userNurse
    , FontAwesome.Solid.userPlus
    , FontAwesome.Solid.userSecret
    , FontAwesome.Solid.userShield
    , FontAwesome.Solid.userSlash
    , FontAwesome.Solid.userTag
    , FontAwesome.Solid.userTie
    , FontAwesome.Solid.userTimes
    , FontAwesome.Solid.users
    , FontAwesome.Solid.usersCog
    , FontAwesome.Solid.usersSlash
    , FontAwesome.Solid.utensilSpoon
    , FontAwesome.Solid.utensils
    , FontAwesome.Solid.vectorSquare
    , FontAwesome.Solid.venus
    , FontAwesome.Solid.venusDouble
    , FontAwesome.Solid.venusMars
    , FontAwesome.Solid.vial
    , FontAwesome.Solid.vials
    , FontAwesome.Solid.video
    , FontAwesome.Solid.videoSlash
    , FontAwesome.Solid.vihara
    , FontAwesome.Solid.virus
    , FontAwesome.Solid.virusSlash
    , FontAwesome.Solid.viruses
    , FontAwesome.Solid.voicemail
    , FontAwesome.Solid.volleyballBall
    , FontAwesome.Solid.volumeDown
    , FontAwesome.Solid.volumeMute
    , FontAwesome.Solid.volumeOff
    , FontAwesome.Solid.volumeUp
    , FontAwesome.Solid.voteYea
    , FontAwesome.Solid.vrCardboard
    , FontAwesome.Solid.walking
    , FontAwesome.Solid.wallet
    , FontAwesome.Solid.warehouse
    , FontAwesome.Solid.water
    , FontAwesome.Solid.waveSquare
    , FontAwesome.Solid.weight
    , FontAwesome.Solid.weightHanging
    , FontAwesome.Solid.wheelchair
    , FontAwesome.Solid.wifi
    , FontAwesome.Solid.wind
    , FontAwesome.Solid.windowClose
    , FontAwesome.Solid.windowMaximize
    , FontAwesome.Solid.windowMinimize
    , FontAwesome.Solid.windowRestore
    , FontAwesome.Solid.wineBottle
    , FontAwesome.Solid.wineGlass
    , FontAwesome.Solid.wineGlassAlt
    , FontAwesome.Solid.wonSign
    , FontAwesome.Solid.wrench
    , FontAwesome.Solid.xRay
    , FontAwesome.Solid.yenSign
    , FontAwesome.Solid.yinYang
    ]
